services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:ssl
    volumes:
      - web-vol:/var/www/html/
    ports:
      - 443:443
      - 8080:8080
      - 9191:9191
    networks:
      - inception
    depends_on:
      - wordpress
      - mysite
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress:fpm7.4
    volumes:
      - web-vol:/var/www/html/
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb:1.0
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  redis:
    build: requirements/bonus/redis/
    container_name: redis
    image: redis:cache
    networks:
      - inception
    restart: always
  adminer:
    build: requirements/bonus/adminer/
    container_name: adminer
    image: adminer:db
    networks:
      - inception
    volumes:
      - web-vol:/var/www/html/
    restart: always
  ftp:
    build: requirements/bonus/ftp/
    container_name: ftp
    image: ftp:vs
    volumes:
      - web-vol:/var/www/html/
    env_file:
      - .env
    ports:
      - 8181:21
    networks:
      - inception
    restart: always
  grafana:
    build: requirements/bonus/grafana/
    container_name: grafana
    image: grafana:monitor
    ports:
      - 3000:3000
    networks:
      - inception
    restart: always
  mysite:
    build: requirements/bonus/mysite/
    container_name: mysite
    image: mysite:py
    volumes:
      - web-vol:/var/www/html/
    networks:
      - inception
    restart: always

volumes:
  web-vol:
  db-vol:

networks:
  inception:
